# Generated by Django 6.0.2 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "url")},
        ),
    ]
