# Generated by Django 6.0.2 on 2026-03-17 16:37

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_unique_together_alter_company_name_and_more"),
        ("source", "0002_alter_source_created_on_alter_source_name_and_more"),
        ("story", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="story",
            new_name="story_body_text_gin_idx",
            old_name="story_body_text_trgm_gin",
        ),
        migrations.AlterField(
            model_name="story",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_stories",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(max_length=1500),
        ),
        migrations.AddIndex(
            model_name="story",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="story_title_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
