# Generated by Django 6.0.2 on 2026-03-10 10:21

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("source", "0001_initial"),
        ("story", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="story",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["body_text"],
                name="story_body_text_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
