# Generated by Django 6.0.2 on 2026-03-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_story_story_body_text_trgm_gin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["created_on"]},
        ),
    ]
