# Generated by Django 6.0.2 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_alter_story_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
