# Generated by Django 6.0.2 on 2026-03-17 16:37

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name="company",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="company_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
