# Generated by Django 6.0.2 on 2026-03-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["created_on"]},
        ),
    ]
