# Generated by Django 6.0.2 on 2026-03-17 16:37

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_unique_together_alter_company_name_and_more"),
        ("source", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="source",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="source_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
