# Generated by Django 6.0.2 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0002_alter_source_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
